import { CubeModel, type MoveName } from './CubeModel';

export interface GraphNode {
  id: string;
  label: string;
  depth: number;
  moves: MoveName[];
  cube: CubeModel;
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
}

export interface GraphEdge {
  source: string;
  target: string;
  move: MoveName;
}

export interface SubgraphData {
  name: string;
  description: string;
  generators: MoveName[];
  nodes: GraphNode[];
  edges: GraphEdge[];
  diameter: number;
  rootId: string;
}

export type SubgroupData = SubgraphData;

export interface BFSResult {
  exploredOrder: string[]; // Order in which nodes were popped from queue
  pathNodeIds: string[]; // Shortest path node IDs from start to target
  pathMoves: MoveName[]; // Move sequence from start to target
  depthReached: number;
}

export class SubgroupGenerator {
  // Generate the 3-involution Checkerboard Slice Subgraph <M2, E2, S2>
  // Isomorphic to (Z_2)^3, forming a 3D Cube graph (order 8, degree 3, diameter 3)
  static generateCheckerboardSubgraph(): SubgroupData {
    return this.buildSubgraph(
      'Checkerboard Subgroup ⟨M2, E2, S2⟩',
      'The elementary abelian 3-generator group (Z₂³). Forms a stunning 3D hypercube graph of 8 states where every generator is an involution (g = g⁻¹). Distance 3 is the famous 6-face checkerboard!',
      ['M2', 'E2', 'S2'],
      10
    );
  }

  // Generate the <R2, U2> Subgroup (Order 6, Hexagonal cycle)
  static generateR2U2Subgraph(): SubgroupData {
    return this.buildSubgraph(
      'R²-U² Hexagonal Subgroup ⟨R2, U2⟩',
      'A dihedral-type cycle of order 6 generated by 180° turns of R and U. Notice how alternating R2 and U2 returns exactly to the solved state in 6 moves, forming a regular 6-cycle.',
      ['R2', 'U2'],
      8
    );
  }

  // Generate the Sexy Move Commutator Orbit <(R U R' U')>
  static generateCommutatorOrbit(): SubgroupData {
    const cube = new CubeModel();
    const sexyMove = CubeModel.parseAlgorithm("R U R' U'");
    const nodes: GraphNode[] = [];
    const edges: GraphEdge[] = [];

    let current = cube.clone();
    for (let i = 0; i < 6; i++) {
      const id = i === 0 ? 'solved' : `c_${i}`;
      const label = i === 0 ? 'Solved (e)' : `(R U R' U')^${i}`;
      nodes.push({
        id,
        label,
        depth: i <= 3 ? i : 6 - i,
        moves: i === 0 ? [] : (Array(i).fill(sexyMove).flat() as MoveName[]),
        cube: current.clone(),
      });
      const next = current.clone();
      next.applyAlgorithm(sexyMove);
      const nextId = i === 5 ? 'solved' : `c_${i + 1}`;
      edges.push({
        source: id,
        target: nextId,
        move: "R", // representative
      });
      current = next;
    }

    return {
      name: "Commutator Orbit ⟨(R U R' U')⟩",
      description:
        "The celebrated 4-move 'Sexy Move' commutator [R, U] = R U R' U' has an exact order of 6. Applying it 6 times traverses a 6-node cycle and returns to identity!",
      generators: ['R', 'U'],
      nodes,
      edges,
      diameter: 3,
      rootId: 'solved',
    };
  }

  // Generic Subgraph BFS builder from generators
  static buildSubgraph(
    name: string,
    description: string,
    generators: MoveName[],
    maxNodes = 64
  ): SubgroupData {
    const rootCube = new CubeModel();
    const rootFp = rootCube.getFingerprint();
    const rootId = 'node_0';

    const nodeMap = new Map<string, GraphNode>();
    const fpToId = new Map<string, string>();
    fpToId.set(rootFp, rootId);

    const rootNode: GraphNode = {
      id: rootId,
      label: 'Solved (e)',
      depth: 0,
      moves: [],
      cube: rootCube.clone(),
    };
    nodeMap.set(rootId, rootNode);

    const edges: GraphEdge[] = [];
    const queue: string[] = [rootId];
    let maxDepth = 0;

    while (queue.length > 0 && nodeMap.size < maxNodes) {
      const currentId = queue.shift()!;
      const current = nodeMap.get(currentId)!;

      for (const move of generators) {
        const nextCube = current.cube.clone();
        nextCube.applyMove(move);
        const nextFp = nextCube.getFingerprint();

        let nextId = fpToId.get(nextFp);
        if (!nextId) {
          if (nodeMap.size >= maxNodes) continue;
          nextId = `node_${nodeMap.size}`;
          fpToId.set(nextFp, nextId);
          const nextMoves = [...current.moves, move];
          const nextNode: GraphNode = {
            id: nextId,
            label: nextMoves.join(' '),
            depth: current.depth + 1,
            moves: nextMoves,
            cube: nextCube,
          };
          nodeMap.set(nextId, nextNode);
          maxDepth = Math.max(maxDepth, nextNode.depth);
          queue.push(nextId);
        }

        // Add edge if not already present
        const edgeExists = edges.some(
          (e) =>
            (e.source === currentId && e.target === nextId && e.move === move) ||
            (e.source === nextId && e.target === currentId && e.move === move)
        );
        if (!edgeExists) {
          edges.push({
            source: currentId,
            target: nextId,
            move,
          });
        }
      }
    }

    // Position nodes radially / on a circle for immediate clean layout
    const nodes = Array.from(nodeMap.values());
    const n = nodes.length;
    const radius = 170;
    nodes.forEach((node, i) => {
      if (node.id === rootId) {
        node.x = 220;
        node.y = 220;
      } else {
        const angle = (2 * Math.PI * (i - 1)) / (n - 1);
        node.x = 220 + radius * Math.cos(angle);
        node.y = 220 + radius * Math.sin(angle);
      }
    });

    return {
      name,
      description,
      generators,
      nodes,
      edges,
      diameter: maxDepth,
      rootId,
    };
  }

  // Live Breadth-First Search on a subgraph
  static runBFS(subgraph: SubgroupData, startId: string, targetId: string): BFSResult {
    const queue: string[] = [startId];
    const visited = new Set<string>([startId]);
    const parentMap = new Map<string, { parentId: string; move: MoveName }>();
    const exploredOrder: string[] = [];

    while (queue.length > 0) {
      const curr = queue.shift()!;
      exploredOrder.push(curr);

      if (curr === targetId) {
        break;
      }

      // Find adjacent edges
      for (const edge of subgraph.edges) {
        let neighbor: string | null = null;
        let move = edge.move;

        if (edge.source === curr) {
          neighbor = edge.target;
        } else if (edge.target === curr) {
          neighbor = edge.source;
          // Invert move if traversing backwards
          move = CubeModel.invertAlgorithm([move])[0];
        }

        if (neighbor && !visited.has(neighbor)) {
          visited.add(neighbor);
          parentMap.set(neighbor, { parentId: curr, move });
          queue.push(neighbor);
        }
      }
    }

    // Backtrack path from target to start
    const pathNodeIds: string[] = [];
    const pathMoves: MoveName[] = [];
    let curr = targetId;

    if (visited.has(targetId)) {
      pathNodeIds.unshift(curr);
      while (curr !== startId && parentMap.has(curr)) {
        const { parentId, move } = parentMap.get(curr)!;
        pathMoves.unshift(move);
        pathNodeIds.unshift(parentId);
        curr = parentId;
      }
    }

    return {
      exploredOrder,
      pathNodeIds,
      pathMoves,
      depthReached: pathMoves.length,
    };
  }
}
